### ISSUE TITLE
Cant read `geometry` type field from `org.opensextant.giscore.filegdb.Table`

### ISSUE THREAD

**Issue by ZeroGraviti** [OpenSextant/giscore#8]
I can't seem to be able to get `geometry` type fields from a `Table` opened on a FileGDB. Can someone help me use the API correctly for this ?
The field type in question is `geometry (MultiLineString,4326)`
TIA

**Comment by rdrand** [comment]
I did the original giscore, and filegdb support has always been problematic because ESRI would make small non-compatible changes to the format. The format itself wasn't public, so we couldn't write our own access library and their libraries were version specific. If all that is breaking is MultiLineString I'm truly grateful to ESRI for not breaking more.

The version here is based on their released unencumbered libraries, but the last work I did on that 
is now four years old. I would love someone to update and retest with whatever updates have happened with filegdb. 

An unfortunate fact of life is that I no longer am working in an area that would fund me spending the time to do the work. 

If you or someone you know wishes to, please create a fork and I'll look at any pull request. It unfortunately is a complex piece of work requiring shared libraries to be built on MacOS, Linux and Windows.
